apiVersion: v1
kind: ConfigMap
metadata:
  name: prefect-server-config
  namespace: default
data:
  PREFECT_SERVER__DB_CONNECTION_URL: "postgresql://user:password@postgresql-service:5432/prefect"
  PREFECT_API_URL: "http://prefect-server.default.svc.cluster.local:4200"
  PREFECT_SERVER__GRAPHQL_URL: "http://prefect-server.default.svc.cluster.local:4200/graphql"
  PREFECT_SERVER__UI__API_URL: "http://prefect-server.default.svc.cluster.local:4200/graphql"
  PREFECT_SERVER__TELEMETRY__ENABLED: "false"
